name: taskmanager
description: "A comprehensive task management app with Firebase integration"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # Firebase Integration
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # State Management
  provider: ^6.1.2
  
  # Image and File Handling
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  path: ^1.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/utils/tasklogo.webp

