// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhvqCEnBxS1qmf6SPypzhGU2rLE_5fxo',
    appId: '1:446982167094:web:27a46c6d742c826666d697',
    messagingSenderId: '446982167094',
    projectId: 'todo-78efd',
    authDomain: 'todo-78efd.firebaseapp.com',
    databaseURL: 'https://todo-78efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-78efd.firebasestorage.app',
    measurementId: 'G-Y1T56FVLDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARuA8EzPF4TdOaQRd8_TkGNIbSWM1PHlQ',
    appId: '1:446982167094:android:b7cabb146532ee2c66d697',
    messagingSenderId: '446982167094',
    projectId: 'todo-78efd',
    databaseURL: 'https://todo-78efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-78efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvHutUPs4pSI6-PUzjZ-CeuVLxdfbHBw',
    appId: '1:446982167094:ios:e4ae5035bc5d2e8866d697',
    messagingSenderId: '446982167094',
    projectId: 'todo-78efd',
    databaseURL: 'https://todo-78efd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-78efd.firebasestorage.app',
    iosBundleId: 'com.nikh.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );
}